config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :subscribes
  resources :categories, param: :slug
  resources :images, param: :slug
  resources :likes
  resources :comments
  resources :accounts
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, param: :slug, controllers: {
      registrations: 'users/registrations', sessions: 'users/sessions'#,
      #omniauth_callbacks: 'callbacks'
  }
  get '/auth/:provider/callback', to: 'callbacks#create'
  authenticated :user do
    root 'categories#index', as: :authenticated_root
  end
  root 'welcome#index'
  mount Resque::Server, at: 'admin/resque'
  post 'language', to: 'application#language'
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :image
  belongs_to :category, counter_cache: true
  validates :image_id, :user_id, :category_id, presence: true
  validates :user_id, uniqueness: { scope: :image_id }
end

app/controllers/likes_controller.rb
# frozen_string_literal: true

class LikesController < InheritedResources::Base
  before_action :authenticate_user!
  before_action :like_params, only: :create

  def create
    @like_old = Like.where(user_id: current_user.id, image_id: like_params[:image_id]).first
    respond_to do |format|
      if @like_old
        format.js     { render status: :found }
        format.json   { render status: :found }
      else
        @like = current_user.likes.new(like_params)
        if @like.save
          @image = @like.image
          format.js     { render status: :created }
          format.json   { render status: :created }
        else
          format.js   { render status: :bad_request }
        end
      end
    end
  end

  def destroy
    @like = Like.find(params[:id])
    respond_to do |format|
      if current_user.id == @like.user_id
        @image = @like.image
        if @like.destroy!
          format.js   { render status: :accepted }
        else
          format.js   { render status: :bad_request }
        end
      else
        format.js   { render status: :forbidden }
      end
    end
  end

  private

  def like_params
    params.require(:like).permit(:image_id, :category_id)
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_form.html.haml
- if @like
  = render 'likes/unlike_form'
- else
  = render 'likes/like_form'

app/views/likes/_like_form.html.haml
= form_for [Like.new], remote: true do |f|
  .field
    = f.hidden_field :image_id, value: @image.id
    = f.hidden_field :category_id, value: @image.category_id
  .actions
    = f.button @image.likes.size, class: 'btn btn-outline-dark fa fa-heart'

app/views/likes/_unlike_form.html.haml
= button_to like_path(id: @like.id),  method: :delete, remote: true, class: 'btn btn-outline-success fa fa-heart' do
  = "#{@image.likes.size}"

app/views/likes/create.js.erb
<% unless @like.errors.any? %>
  var likeBlock = document.getElementById("image-likes");
  while (likeBlock.firstChild) {
      likeBlock.removeChild(likeBlock.firstChild);
  }
  $('.like-form').prepend("<%= escape_javascript render 'likes/unlike_form' %>");
<% end %>

app/views/likes/destroy.js.erb
<% unless @image.nil? %>
  var likeBlock = document.getElementById("image-likes");
  while (likeBlock.firstChild) {
      likeBlock.removeChild(likeBlock.firstChild);
  }
  $('.like-form').prepend("<%= escape_javascript render partial: 'likes/like_form' %>");
<% end %>