config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :subscribes
  resources :categories, param: :slug
  resources :images, param: :slug
  resources :likes
  resources :comments
  resources :accounts
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, param: :slug, controllers: {
      registrations: 'users/registrations', sessions: 'users/sessions'#,
      #omniauth_callbacks: 'callbacks'
  }
  get '/auth/:provider/callback', to: 'callbacks#create'
  authenticated :user do
    root 'categories#index', as: :authenticated_root
  end
  root 'welcome#index'
  mount Resque::Server, at: 'admin/resque'
  post 'language', to: 'application#language'
end

app/models/category.rb
class Category < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  belongs_to :user
  has_many :images, dependent: :delete_all
  has_many :subscribes, dependent: :delete_all
  has_many :comments, dependent: :delete_all
  has_many :likes, dependent: :delete_all

  validates :title, presence: true

end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < InheritedResources::Base
  before_action :authenticate_user!
  before_action :find_category, except: %i[index new create]

  def index
    @categories = Category.page(params[:page]).per(6)
  end

  def show
    @images = @category.images.page(params[:page]).per(6)
    respond_with @images
  end

  def new
    @category = Category.new
  end

  def create
    @category = current_user.categories.new category_params
    respond_to do |format|
      if @category.save
        format.html do
          redirect_to(@category, success: t('controllers.categories.created'))
        end
        format.json do
          render json: @category, status: :created, location: @category
        end
      else
        format.html { render action: 'new' }
        format.json do
          render json: @category.errors, danger: :unprocessable_entity
        end
      end
    end
  end

  def edit; end

  def update
    respond_to do |format|
      if @category.user_id == current_user.id
        if @category.update!(category_params)
          alert_success t('controllers.categories.updated')
          format.html { redirect_to category_path(@category) }
        end
      else
        format.html { render :edit, status: :forbidden }
      end
    end
  end

  def delete; end

  def destroy
    respond_to do |format|
      if @category.user_id == current_user.id
        if @category.destroy!
          alert_success t('controllers.categories.deleted')
          format.html { redirect_to categories_path }
        end
      else
        format.html { render :index, status: :forbidden }
      end
    end
  end

  private

  # BEFORE ACTIONS

  def find_category
    @category = Category.friendly.find(params[:slug])
    @subscribe = @category.subscribes.find_by(user_id: current_user.id)
  end

  # PARAMS FINDER

  def category_params
    params.require(:category).permit(:title)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.haml
= form_for @category do |f|
  - if @category.errors.any?
    #error_explanation
      %h2= "#{pluralize(@category.errors.count, "error")} prohibited this category from being saved:"
      %ul
        - @category.errors.full_messages.each do |message|
          %li= message
  = f.text_field :title, placeholder: t('categories.form.image_title'), class: 'form-control'
  %br
  .actions
    = f.submit t('categories.form.save'), class: 'btn btn-success'

app/views/categories/edit.html.haml
.category-editor
  .category-content
    .container
      .text-center
        %h2
          = "#{t('categories.edit.editing')} #{@category.title}"
        .category-manage
          = render 'form'

app/views/categories/index.html.haml
.categories
  .text-center
    %h2
      =t('categories.index.title')
  .container-fluid
    .row
      - @categories.each do |category|
        .card.col-sm-6.col-lg-4
          .card-wrapper
            .card-img
              %a.picture{href: category_path(category.slug), style: "background: url(#{category.images.last&.file_path&.url || asset_url('picture.png')}) center center no-repeat; background-size: cover;"}

              .card-img-overlay.d-block.d-lg-none.d-xl-none
                %h5.card-title
                  = link_to category.title, category
                %h6.card-subtitle{'data-toggle': 'tooltip', 'data-placement': 'top', 'title': 'Last time updated'}
                  ="#{category.images.last.created_at.strftime("%d/%m/%Y") unless category.images.last.nil?}"
                %p.card-text{'data-toggle': 'tooltip', 'data-placement': 'top', 'title': 'Owner of this category'}
                  = category.user.username
  .categories-footer
    .center-horizontal
      = paginate @categories

app/views/categories/new.html.haml
.categories
  .text-center
    %h2
      =t('categories.new.new')
  .container
    .creator-form.text-center
      = render 'form'

app/views/categories/show.html.haml
.categories
  .top-block.text-center
    .title
      %h2
        = @category.title
    .manage
      .subscribe-form#category-subscribe
        = render partial: 'subscribes/form', review: Subscribe.new(category_id: @category.id)
      -if current_user.id == @category.user_id
        = link_to t('categories.index.edit'), edit_category_path(@category.slug), class: 'btn btn-outline-warning'
        = link_to t('categories.index.destroy'), @category, method: :delete, data: { confirm: t('deleting.confirmation') }, class: 'btn btn-outline-danger'
  -if current_user.id == @category.user_id
    %br
    %br
  .container-fluid
    .row
      - @images.each do |image|
        .card.col-sm-6.col-lg-4
          .card-wrapper
            .card-img
              %a.picture{href: image_path(image.slug), style: "background: url(#{image.file_path.url(:large)}) center center no-repeat; background-size: cover;"}
              .card-img-overlay.d-block.d-lg-none.d-xl-none
                %h5.card-title.text-truncate
                  = link_to image.title, image
                %h6.card-subtitle{'data-toggle': 'tooltip', 'data-placement': 'top', 'title': 'Created'}
                  =image.created_at.strftime("%d/%m/%Y")
                %p.card-text{'data-toggle': 'tooltip', 'data-placement': 'top', 'title': 'Owner of this category'}
                  = image.user.username
  .categories-footer
    .center-horizontal
      = paginate @images