config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :subscribes
  resources :categories, param: :slug
  resources :images, param: :slug
  resources :likes
  resources :comments
  resources :accounts
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, param: :slug, controllers: {
      registrations: 'users/registrations', sessions: 'users/sessions'#,
      #omniauth_callbacks: 'callbacks'
  }
  get '/auth/:provider/callback', to: 'callbacks#create'
  authenticated :user do
    root 'categories#index', as: :authenticated_root
  end
  root 'welcome#index'
  mount Resque::Server, at: 'admin/resque'
  post 'language', to: 'application#language'
end

app/models/subscribe.rb
class Subscribe < ApplicationRecord
  belongs_to :user
  belongs_to :category

  validates :user_id, :category_id, presence: true

  after_save :send_confirmation

  def send_confirmation
    Resque.enqueue(SubscribeNotification, id)
  end

end

app/controllers/subscribes_controller.rb
# frozen_string_literal: true

class SubscribesController < InheritedResources::Base
  before_action :authenticate_user!
  before_action :subscribe_params, only: :create

  def create
    @subscribe_old = current_user.subscribes.where(subscribe_params).first
    respond_to do |format|
      unless @subscribe_old
        @subscribe = current_user.subscribes.new subscribe_params
        if @subscribe.save
          @category = Category.find(subscribe_params[:category_id])
          format.js   { }
        end
      end
    end
  end

  def destroy
    @subscribe = Subscribe.find(params[:id])
    respond_to do |format|
      if current_user.id == @subscribe.user_id
        if @subscribe.destroy!
          @category = Category.find(params[:category_id])
          format.js   { render status: :accepted }
        else
          format.js   { render status: :bad_request }
        end
      else
        format.js   { render status: :forbidden }
      end
    end
  end

  private

  def subscribe_params
    params.require(:subscribe).permit(:category_id)
  end
end

app/helpers/subscribes_helper.rb
module SubscribesHelper
end

app/views/subscribes/_form.html.haml
- if @subscribe
  = render 'subscribes/unsubscribe'
- else
  = render 'subscribes/subscribe'

app/views/subscribes/_subscribe.html.haml
= form_for [Subscribe.new], remote: true do |f|
  .field
    = f.hidden_field :category_id, value: @category.id
    = f.hidden_field :user_id, value: current_user.id
  .actions
    = f.button t('subscribes.subscribe'), class: 'btn btn-outline-dark fa fa-bell'

app/views/subscribes/_unsubscribe.html.haml
= button_to subscribe_path(id: @subscribe.id, category_id: @category.id),  method: :delete, remote: true, class: 'btn btn-outline-danger fa fa-bell-slash' do
  = t('subscribes.unsubscribe')

app/views/subscribes/create.js.erb
var subscribeBlock = document.getElementById("category-subscribe");
while (subscribeBlock.firstChild) {
    subscribeBlock.removeChild(subscribeBlock.firstChild);
}
$('.subscribe-form').prepend("<%= escape_javascript render 'subscribes/unsubscribe', review: Subscribe.new(user_id: current_user.id, category_id: @category.id) %>")

app/views/subscribes/destroy.js.erb
var subscribeBlock = document.getElementById("category-subscribe");
while (subscribeBlock.firstChild) {
    subscribeBlock.removeChild(subscribeBlock.firstChild);
}
$('.subscribe-form').prepend("<%= escape_javascript render partial: 'subscribes/subscribe' %>")