config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :subscribes
  resources :categories, param: :slug
  resources :images, param: :slug
  resources :likes
  resources :comments
  resources :accounts
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, param: :slug, controllers: {
      registrations: 'users/registrations', sessions: 'users/sessions'#,
      #omniauth_callbacks: 'callbacks'
  }
  get '/auth/:provider/callback', to: 'callbacks#create'
  authenticated :user do
    root 'categories#index', as: :authenticated_root
  end
  root 'welcome#index'
  mount Resque::Server, at: 'admin/resque'
  post 'language', to: 'application#language'
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user

  validates :user_id, :provider, :uid, presence: true

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable,
         :validatable, authentication_keys: [:login]

  attr_writer :login

  def login
    @login || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(email) = :value", { value: login.downcase }]).first
    elsif conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  belongs_to :user
  has_many :images, dependent: :delete_all
  has_many :subscribes, dependent: :delete_all
  has_many :comments, dependent: :delete_all
  has_many :likes, dependent: :delete_all

  validates :title, presence: true

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :image
  belongs_to :category, counter_cache: true
  validates :body, :image_id, :user_id, :category_id, presence: true
end

app/models/image.rb
# frozen_string_literal: true

class Image < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  mount_uploader :file_path, ImageUploader

  belongs_to :user
  belongs_to :category, counter_cache: true
  has_many :comments
  has_many :likes

  validates :file_path, :title, :user_id, :category_id, presence: true

  after_save :send_updates

  def send_updates
    Resque.enqueue(ImageUpdates, id)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :image
  belongs_to :category, counter_cache: true
  validates :image_id, :user_id, :category_id, presence: true
  validates :user_id, uniqueness: { scope: :image_id }
end

app/models/subscribe.rb
class Subscribe < ApplicationRecord
  belongs_to :user
  belongs_to :category

  validates :user_id, :category_id, presence: true

  after_save :send_confirmation

  def send_confirmation
    Resque.enqueue(SubscribeNotification, id)
  end

end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  extend FriendlyId
  friendly_id :username, use: :slugged
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,
         :validatable, authentication_keys: [:login]

  attr_writer :login

  before_destroy :delete_linked_accounts

  has_many :accounts
  has_many :categories, dependent: :delete_all
  has_many :subscribes, dependent: :delete_all
  has_many :images
  has_many :comments
  has_many :likes

  validates :username, presence: :true, uniqueness: { case_sensitive: false }

  def login
    @login || self.username || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { value: login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end

  def self.from_omniauth(auth)
    user_email = auth.info.email || "#{auth.info.nickname || auth.info.name}@#{auth.provider}.com"
    user = User.find_by_email(user_email)
    if user.nil?
      #create user and account
      user = User.create!(email: user_email, password: Devise.friendly_token[0,20], autogenerated: true,
                          username: auth.info.nickname || "#{auth.info.name}_#{auth.provider}")
    end
    #add account to exist user
    account = Account.where(provider: auth.provider, uid: auth.uid).first_or_create
    account.provider = auth.provider
    account.uid = auth.uid
    account.user_id = user.id
    account.save
    user
  end

  def delete_linked_accounts
    Account.where(user_id: id).all.destroy_all
  end


end

app/models/user_activity.rb
class UserActivity < ApplicationRecord
  belongs_to :user
end

app/controllers/images_controller.rb
# frozen_string_literal: true

class ImagesController < InheritedResources::Base
  before_action :authenticate_user!

  def index
    @images = Image.where.not(category_id: nil).page(params[:page]).per(15)
  end

  def show
    @image = Image.friendly.find(params[:slug])
    @comments = @image.comments.order('created_at DESC').page(params[:page]).per(10)
    @like = @image.likes.find_by(user_id: current_user.id)
  end

  def new
    @image = Image.new
    @categories = Category.friendly.all
  end

  def create
    @image = current_user.images.new(images_params)
    respond_to do |format|
      if @image.save
        format.html do
          redirect_to image_path @image, success: t('controllers.images.uploaded')
        end
        format.json do
          render json: @image, status: :created, location: @image
        end
      else
        format.html  do
          flash[:danger] = @image.errors
          redirect_to new_image_path
        end
        format.json
      end
    end
  end

  private

  def images_params
    params.require(:image).permit(:file_path, :title, :category_id)
  end
end

app/controllers/likes_controller.rb
# frozen_string_literal: true

class LikesController < InheritedResources::Base
  before_action :authenticate_user!
  before_action :like_params, only: :create

  def create
    @like_old = Like.where(user_id: current_user.id, image_id: like_params[:image_id]).first
    respond_to do |format|
      if @like_old
        format.js     { render status: :found }
        format.json   { render status: :found }
      else
        @like = current_user.likes.new(like_params)
        if @like.save
          @image = @like.image
          format.js     { render status: :created }
          format.json   { render status: :created }
        else
          format.js   { render status: :bad_request }
        end
      end
    end
  end

  def destroy
    @like = Like.find(params[:id])
    respond_to do |format|
      if current_user.id == @like.user_id
        @image = @like.image
        if @like.destroy!
          format.js   { render status: :accepted }
        else
          format.js   { render status: :bad_request }
        end
      else
        format.js   { render status: :forbidden }
      end
    end
  end

  private

  def like_params
    params.require(:like).permit(:image_id, :category_id)
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/subscribes_helper.rb
module SubscribesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.haml
%footer.page-footer.font-small.indigo.pt-0
  .footer-copyright.py-3.text-center
    = link_to "© #{Date.today.year} Tivgres Gallery", root_path

app/views/layouts/_header.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  =link_to 'Gallery', root_path, class: 'navbar-brand'
  %button.navbar-toggler{'aria-controls': 'navbarTogglerDemo02', 'aria-expanded': 'false',
   'aria-label': 'Toggle navigation', 'data-target': '#navbarToggler',
    'data-toggle': 'collapse', type: 'button'}
    %span.navbar-toggler-icon
  #navbarToggler.collapse.navbar-collapse
    .navbar-nav.mr-auto.mt-2.mt-lg-0
    - if current_user
      %span.link.pointable{'data-target': '#creator', 'data-toggle': 'modal'}
        .nav-item
          %button.btn.btn-outline-success
            =t('header.creator')
      = render 'layouts/modal', { modal_id: 'creator', modal_title: t('header.creator') } do
        .modal-body
          .row
            .col-6
              .text-center
                = link_to t('header.category_create'), new_category_path,  class: 'btn btn-outline-success'
            .col-6
              .text-center
                = link_to t('header.image_upload'), new_image_path,  class: 'btn btn-outline-success'
      %span.link.pointable{'data-target': '#categories', 'data-toggle': 'modal'}
        .nav-item
          %button.btn.btn-outline-dark
            =t('header.categories')
      = render 'layouts/modal', { modal_id: 'categories', modal_title: t('header.categories_popular') } do
        .modal-body
          - @categories_header.each do |category|
            %hr
              %h3.text-center
                = link_to category.title, category
      .nav-item.dropdown
        = link_to t('header.pictures'), images_path, class: 'btn btn-outline-dark'
      .nav-item
        = link_to t('header.comments'), comments_path, class: 'btn btn-outline-dark'
      %span.link.pointable{'data-target': '#account', 'data-toggle': 'modal'}
        .nav-item
          %button.btn.btn-outline-danger
            =t('header.account')
      = render 'layouts/modal', { modal_id: 'account', modal_title: t('header.account') } do
        .modal-body
          .row
            .col-sm-12.col-md-6
              .text-center
                = link_to t('header.edit'), edit_user_registration_path, class: 'btn btn-outline-warning'
            .col-sm-12.col-md-6
              .text-center
                = link_to t('header.log_out'), destroy_user_session_path, method: :delete, class: 'btn btn-outline-danger'
    - else
      .entry.my-2.my-lg-0
        = link_to t('header.log_in'), new_user_session_path, class: 'btn btn-primary mr-sm-2'
        = link_to t('header.sign_up'), new_user_registration_path, class: 'btn btn-info my-2 mr-sm-2'
    %span.link.pointable{'data-target': '#editLanguage', 'data-toggle': 'modal'}
      .nav-item.my-2.my-sm-0
        %button.btn.btn-outline-light{style: "background: url(http://www.countryflags.io/#{@current_country}/shiny/32.png); background-repeat: no-repeat; margin: auto; background-size: auto; background-position: center; "}
    = render 'layouts/modal', { modal_id: 'editLanguage', modal_title: 'Edit Language' } do
      .modal-body
        - @available_languages.each_with_index do |lang_code, index|
          - unless lang_code.eql?(@current_language)
            =button_to '', language_path(lang_code: lang_code), method: :post, class: 'dropdown-item',
               style: "background: url(http://www.countryflags.io/#{@linked_countries[index]}/shiny/32.png); background-repeat: no-repeat; margin: auto; background-size: auto; background-position: center;"

app/views/layouts/_modal.html.haml
.modal.fade{'aria-labelledby': 'myModalLabel', role: 'dialog', tabindex: '-1', id: modal_id}
  .modal-dialog{role: :document}
    .modal-content
      .modal-header
        %h5.modal-title= modal_title
        %button.close{'aria-label': 'Close', 'data-dismiss': :modal, type: 'button'}
          %span{'aria-hidden': true} ×

      = yield

app/views/layouts/_notification.html.haml
- flash.each do |name, message|
  %div{class: name}
    %p= message

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: 'text/html; charset=UTF-8', 'http-equiv': 'Content-Type'}
    %meta{name: 'viewport', content: 'width=device-width, initial-scale=1, shrink-to-fit=no'}
    %title Gallery
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .wrapper
      .header
        = render 'layouts/header'
      .notification
        = render 'layouts/notification'
      .content
        = yield
      .footer
        = render 'layouts/footer'